package Assignment2;
import java.util.*;
public enum ApparatusType{
    LEGPRESSMACHINE , BARBELL , HACKSQUATMACHINE , LEGEXTENSIONMACHINE ,
     LEGCURLMACHINE , LATPULLDOWNMACHINE , PECDECKMACHINE ,
     CABLECROSSOVERMACHINE
}
